# Dependencies
markdown:         redcarpet
highlighter:      true

# Permalinks
permalink:        /:categories/:title

# Setup
title:            Nerditya
tagline:          'by Aditya'
description:      'Random musings of a coffee lover, photographer, engineer, geek.'
url:              http://nerditya.com
baseurl:          '/'
paginate:         1

author:
  name:           'Aditya Shevade'
  url:            https://twitter.com/adibis

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/lanyon
