# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Site configuration
title:            'Nerditya'
tagline:          'by Aditya'
description:      'Random musings of a coffee lover, photographer, engineer, geek.'
url:              'http://nerditya.com'
baseurl:          '/'
paginate:         1

# Social Media Settings
twitter_username: adibis
github_username:  adibis

# Permalinks
permalink:        /:categories/:title/

author:
  name:           'Aditya Shevade'
  url:            https://twitter.com/adibis
  email:          aditya.shevade@gmail.com

gems: [jekyll-paginate, jekyll-sitemap]

# Build settings
markdown:         redcarpet
highlighter:      pygments

# Custom vars
version:          1.0.0
